### ISSUE TITLE
Security Vulnerability Found in Silverpeas DockerHub Latest Version

### ISSUE THREAD

**Issue by MAneesh2324** [Silverpeas/docker-silverpeas-prod#7]
Hi Silverpeas Team,

My name is Maneesh, and I am a security researcher. During an assessment of the latest version of Silverpeas on DockerHub, I discovered a potential security vulnerability.

Could you please let me know the appropriate channel to submit a detailed report?

**Comment by mmoqui** [comment]
Hi Maneesh, we have an [issue tracker](https://tracker.silverpeas.org/) in which you can report your finding. For doing, you can ask for an account creation in our issue tracker. Please fill correctly information about you (otherwise your account creation request will be refused). 
Once your account validated, you could open your vulnerability issues in the Security project.

**Comment by MAneesh2324** [comment]
i have created a account (manu1234pqrs@gmail.com) and is pending by admin

**Comment by mmoqui** [comment]
You didn't specify the company or the university you work for

**Comment by MAneesh2324** [comment]
i m an independent researcher

**Comment by MAneesh2324** [comment]
what should i specify on the company? i m currently studying at university of hertfordshire.. please accept the invitation

**Comment by mmoqui** [comment]
Ok, I set Freelance. Your account is enabled
